Added in unittests: executing all unittests in alphabetical order and then generating output files with each executed test

diff --git a/.github/workflows/smoketest.yml b/.github/workflows/smoketest.yml
--- a/.github/workflows/smoketest.yml
+++ b/.github/workflows/smoketest.yml
@@ -534,18 +534,53 @@ jobs:
         sudo apt-get install -y ${{ env.OS_DEPENDENCIES }}
         sudo apt-get install -y gdb
 
-        curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
-        sudo apt-get install -y nodejs
+        #Remove Node JS as it is unecessary curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
+        #sudo apt-get install -y nodejs
 
-        echo "node.js version = $(node --version), npm version = $(npm --version), release = $(lsb_release -sc)"
+        echo "norelease = $(lsb_release -sc)"
 
     - name: run
-      timeout-minutes: 10 # generous, expected time is approx 1 min.
+      timeout-minutes: 10 # generous, expected time is approx 1 min. #
       run: |
         export LANG="en_US.UTF-8"
         sudo update-locale
-        tar --zstd -xf install.tgz
-        install/opt/HPCCSystems/bin/unittests
+        tar --zstd -xf install.tgz 
+        
+	#Get list of all unit tests and sort them alphabetically
+        tests=$(install/opt/HPCCSystems/bin/unittests -l | sort)
+        
+        for test_case in $tests; do
+            echo "Running $test_case"
+            start_time=$(date +%s)
+            # Run each test case with a timeout of 5 minutes
+            timeout -k 5m install/opt/HPCCSystems/bin/unittests -e $test_case > $test_case.log
+            exit_code=$?
+            end_time=$(date +%s)
+            time_diff=$(( $end_time - $start_time ))
+            if [[ $exit_code -eq 0 ]]; then
+               echo "$test_case: OK (time: $time_diff sec)"
+            else
+               echo "$test_case: FAILED (time: $time_diff sec)"
+            fi
+        done
+    
+        # Process the logs to generate a summary
+        ok_tests=$(grep -l 'OK' *.log)
+        failed_tests=$(grep -l 'FAILED' *.log)
+        echo "Number of tests executed: $(wc -l <<< "$tests")"
+        echo "Number of OK tests: $(wc -l <<< "$ok_tests")"
+        echo "Number of failed tests: $(wc -l <<< "$failed_tests")"
+        # Create a zip file with all logs and upload it as an artifact
+        zip logs.zip *.log
+        rm *.log
+
+    - uses: actions/upload-artifact@v2
+      with:
+        name: test-logs
+        path: logs.zip
+        
+        
+        
 
   # NB: this doesn't really need the post-setup data files included in install.tgz
   # but as this is relatively quick and in parallel with others, it probably doesn't matter
