Added in unittests: executing all unittests in alphabetical order and then generating output files with each executed test

diff --git a/.github/workflows/smoketest.yml b/.github/workflows/smoketest.yml
--- a/.github/workflows/smoketest.yml
+++ b/.github/workflows/smoketest.yml
@@ -540,7 +540,7 @@ jobs:
         echo "norelease = $(lsb_release -sc)"
 
     - name: run
-      timeout-minutes: 10 # generous, expected time is approx 1 min. #
+      timeout-minutes: 10 # generous, expected time is approx 1 min. 
       run: |
         export LANG="en_US.UTF-8"
         sudo update-locale
@@ -550,18 +550,18 @@ jobs:
         tests=$(install/opt/HPCCSystems/bin/unittests -l | sort)
         
         for test_case in $tests; do
-            echo "Running $test_case"
-            start_time=$(date +%s)
-            # Run each test case with a timeout of 5 minutes
-            timeout -k 5m install/opt/HPCCSystems/bin/unittests -e $test_case > $test_case.log
-            exit_code=$?
-            end_time=$(date +%s)
-            time_diff=$(( $end_time - $start_time ))
-            if [[ $exit_code -eq 0 ]]; then
-               echo "$test_case: OK (time: $time_diff sec)"
-            else
-               echo "$test_case: FAILED (time: $time_diff sec)"
-            fi
+          echo "Running $test_case"
+          start_time=$(date +%s)
+          # Run each test case with a timeout of 5 minutes
+          timeout -k 5m install/opt/HPCCSystems/bin/unittests -e $test_case > $test_case.log
+          exit_code=$?
+          end_time=$(date +%s)
+          time_diff=$(( $end_time - $start_time ))
+          if [[ $exit_code -eq 0 ]]; then
+            echo "$test_case: OK (time: $time_diff sec)"
+          else
+            echo "$test_case: FAILED (time: $time_diff sec)"
+          fi
         done
     
         # Process the logs to generate a summary
